### PR TITLE
Merge pull request #99 from KOLANICH/python_package_setup

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by glebm** [comment]
numpy seems to fall back to distutils:

https://github.com/numpy/numpy/blob/8957f23bd61623e0293df610dfe339e09fb0c653/setup.py#L219-L227

SciPy does something similar

Should this package do the same? Why is this change useful?

**Comment by glebm** [comment]
Nevermind, numpy seems to require setuptools now (I referenced an old commit hash in the comment above).

Still please provide a more detailed explanation.

**Comment by KOLANICH** [comment]
>Why is this change useful?

1. ```python3 ./setup.py bdist_wheel``` works.
2. `setup.cfg` s

**Comment by glebm** [comment]
Does this break any workflows? As far as I can tell, `distutils` are built-in and `setuptools` are not but I don't know much about Python packaging.

**Comment by KOLANICH** [comment]
>Does this break any workflows?

The only workflow miss of `setuptools` breaks I know is when I want to build a wheel manually. For example when I want to build a wheel as a user and then install it as root.

>As far as I can tell, distutils are built-in and setuptools are not but I don't know much about Python packaging.

I can move the metadata back and make a fallback to distutils.

**Comment by glebm** [comment]
Yeah, please do the fall back. I'd rather err on the side of caution here. Thanks.

**Comment by KOLANICH** [comment]
Already done.

**Comment by glebm** [comment]
Thanks @KOLANICH

**Pull request merged**
